- hosts: terraform-ansible
  tasks: 
    - name: instalando python 3 e virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes # executar com sudo
    - name: instalando dependencias com pip (Django e Django rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
    - name: Iniciando projeto 
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
    - name: Alterando o host do settings
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
        

# - hosts: terraform-ansible
#  tasks: 
#    - name: criando o arquivo 
#      copy: 
#        dest: /home/ubuntu/index.html
#        content: <h1>Vai Corinthians !!!! Feito com terraform e ansible</h1>
#    - name: criando servidor
#      shell: "nohup busybox httpd -f -d 8080 &"